### ISSUE TITLE
Publish as a free and open source library

### ISSUE THREAD

**Issue by jtrh** [fyntex/drf-pagination-utils#3]
Publish our custom DRF pagination styles as a free and open source library.

-----

> Use FD CL Data's implementation ([fyntex/fd-cl-data#490](https://github.com/fyntex/fd-cl-data/pull/490)). Ideally, we should put it in a library because the code for FD Secrets Manager would be exactly the same.

@glarrain What do you think about publishing our custom pagination implementation as a free and open source library?

_Originally posted by @jtrh in https://github.com/fyntex/fd-secrets-manager/issues/92#issuecomment-729285855_

@jtrh if it makes it easier for us to do our jobs, sure, let's go ahead. Unless there is some security concern I'm missing...

_Originally posted by @glarrain in https://github.com/fyntex/fd-secrets-manager/issues/92#issuecomment-749089695_

**Comment by jtrobles-cdd** [comment]
Closed in https://github.com/fyntex/drf-pagination-utils/pull/101.
